// let a: number;
// a = 10;
// console.log(a);
// a = "Hello";
// console.log(a);

// let a: string;
// const b: number = 10;
// var c: boolean = false;

// a = "Hello";
// c = true;
// console.log(a);
// console.log(c);
// a = 10;
// b = "World";
// c = "false";
// let d: any;
// d = 10;
// console.log(d);
// d = "Hello";
// console.log(d);
// let arr: Array<number> = [1, 2, 3];
// console.log(arr);
// arr.push("4");
// let arr2: Array<string | number> = ["a", "b", "c", 1, 2, 3];
// let v: number | string | undefined = 10;  
// let arr_string: string[] = ["a", "b", "c"];
// console.log(arr_string);
// arr_string.push("d");
// console.log(arr_string);  